# Generated by Django 2.2.7 on 2019-11-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
